# Human-Readable name for this route
name: Get a Resource

# Human-Readable description for this route
description: |
  Gets a resource from the storage system

authentication:
  - Bearer

# If you want to allow the outputs to not be so strictly checked
# sloppy: true

output:
  # For output, we might have multiple
  # types depending on the result of the
  # request. Each output must have a status
  # which is the HTTP Status that corresponds
  # to the schema described
  - status: 200
    body:
      type: object
      required: ['data']
      properties:
        data:
          type: object

  - status: 404
    body:
      error:
        $ref: '#/definitions/HttpError'

  - status: 500
    body:
      error:
        $ref: '#/definitions/HttpError'
