# Human-Readable name for this route
name: <<NAME>>

# Human-Readable description for this route
description: |
  <<DESCRIPTION>>

output:
  - status: 200
    body:
      data:
        type: object
  - status: 500
    body:
      error:
        $ref: '#/definitions/HttpError'
