# Human-Readable name for this route
name: Health Check

# Human-Readable description for this route
description: |
  Allows the caller to see what the health of the
  system is 

# If you want to allow the outputs to not be so strictly checked
# sloppy: true

output:
  # For output, we might have multiple
  # types depending on the result of the
  # request. Each output must have a status
  # which is the HTTP Status that corresponds
  # to the schema described
  - status: 200
    body:
      type: object
      required: ['data']
      properties:
        data:
          type: object
          required: ['uptime']
          properties:
            uptime:
              type: string
              description: The amount of time, in milliseconds, the system has been alive

  - status: 500
    body:
      error:
        $ref: '#/definitions/HttpError'
