# Human-Readable name for this route
name: Check Health of Service

# Human-Readable description for this route
description: |
  This route gives us insight into the health and
  metrics of our system

output:
  - status: 200
    body:
      data:
        uptime:
          type: string
          example: 123ms
  - status: 500
    body:
      error:
        $ref: '#/definitions/HttpError'