# Human-Readable name for this route
name: Health Check

# Human-Readable description for this route
description: |
  Allows the caller to see what the health of the
  system is

tags: ['System']

output:
  - status: 200
    body:
      type: object
      required: ['data']
      properties:
        data:
          type: object
          required: ['uptime']
          properties:
            uptime:
              type: string
              description: The amount of time, in milliseconds, the system has been alive

  - status: 500
    body:
      error:
        $ref: '#/definitions/HttpError'
